In [3]:
import numpy as np
import pandas as pd

In [4]:
print("B. NUMPY\n")
print("1. Membuat Array NumPy 1d dari 100 angka acak antara 1 dan 100. Tentukan Nilai rerata, median, dan standar devisi serta jumlah elemen yang lebh besar dari 500")

# Membuat array 1D dengan 100 angka acak antara 1 dan 100
angka_acak = np.random.randint(1, 1001, size=100)

# Menghitunf rata-rata, median dan stanar deviasi
rata_rata = np.mean(angka_acak)
median = np.median(angka_acak)
standar_deviasi = np.std(angka_acak)

# Menghitunf jumlah elemen yang lebih besar dari 500
jml_lbh_500 = np.sum(angka_acak > 500)

# Mencetak hasil 
print(f"Array Angka Acak: {angka_acak}\n")
print(f"Rata-rata: {rata_rata}\n")
print(f"Median: {median}\n")
print(f"Standar Deviasi: {standar_deviasi}\n")
print(f"Jumlah elemen yang lebih besar dari 500: {jml_lbh_500}\n")


B. NUMPY

1. Membuat Array NumPy 1d dari 100 angka acak antara 1 dan 100. Tentukan Nilai rerata, median, dan standar devisi serta jumlah elemen yang lebh besar dari 500
Array Angka Acak: [123 819  61 830 332 116 850 172 636 990 669 195  79 249 142 206 862 358
 389 821  96 760 578 605 957 635 971 939 355 273 540 263 662 948 695 131
 800 714 379 549 467 284 207 443  71 254 148 597 336 601 499 324 476 974
 192 592 739 579 787 678 574 296 799  83 697 780 647 132 392 307 595 823
 361 337  52 555 856 946 767 625 716 736 818  96 485 138 987 251 968 284
 617 846 474 160 931 592 696 780 682 366]

Rata-rata: 522.44

Median: 576.0

Standar Deviasi: 278.3673946424042

Jumlah elemen yang lebih besar dari 500: 54



In [5]:
print("2. Matriks 4x4 dengan angka acak 0-10 (cari stranspose, determinan, invers )\n")

# Membuat matriks 4x4 dengan angka acak antara 0 dan 10
matriks = np.random.randint(0, 11, size=(4,4))
print (f"Matriks awal:\n{matriks}")

# Transpose matriks
transpose_matriks = np.transpose(matriks)
print(f"\nTranspose matriks:\n {transpose_matriks}")

# Determinan matriks
determinan = np.linalg.det(matriks)
print(f"\nDeterminan matriks: {determinan}")

# Invers matriks 
try:
    invers_matriks = np.linalg.inv(matriks)
    print(f"\nInvers matriks: \n {invers_matriks}")
except np.linalg.LinAlgError:
    print("\nMatriks tidak memiliki invers.")

2. Matriks 4x4 dengan angka acak 0-10 (cari stranspose, determinan, invers )

Matriks awal:
[[5 2 2 7]
 [5 2 3 8]
 [0 4 1 8]
 [3 6 2 3]]

Transpose matriks:
 [[5 5 0 3]
 [2 2 4 6]
 [2 3 1 2]
 [7 8 8 3]]

Determinan matriks: 207.99999999999997

Invers matriks: 
 [[ 0.47115385 -0.28846154 -0.13461538  0.02884615]
 [ 0.08173077 -0.18269231  0.04807692  0.16826923]
 [-1.09615385  1.03846154 -0.11538462  0.09615385]
 [ 0.09615385 -0.03846154  0.11538462 -0.09615385]]


In [6]:
print("3. Membuat array 1D dengan angka 1 - 20. reshape menjadi matriks 4x5 dan hitung nilai maksimum dari setiap baris dan setiap kolom\n")

# Membuat array 1D dari 1 hingga 20
arr_1d = np.arange(1, 21)

# Reshape/mengubah array menjadi matriks 4x5
matriks = arr_1d.reshape(4,5)
print(f"Matriks:\n {matriks}")

# Nilai maksimum setiap baris 
maks_per_baris = np.max(matriks, axis=1)
print(f"\nNilai Maksimum setiap baris: \n {maks_per_baris}")

# Nilai maksimum setiap kolom
maks_per_kolom = np.max(matriks, axis=0)
print(f"\nNilai Maksimum setiap kolom: \n {maks_per_kolom}")


3. Membuat array 1D dengan angka 1 - 20. reshape menjadi matriks 4x5 dan hitung nilai maksimum dari setiap baris dan setiap kolom

Matriks:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Nilai Maksimum setiap baris: 
 [ 5 10 15 20]

Nilai Maksimum setiap kolom: 
 [16 17 18 19 20]


In [7]:
print("4. Membuat 2 matriks 3x3 dengan angka acak dan lakukan operasi (menambahkan kedua matriks, mengalikan kedua matriks secara element-wise, mengkalikan matriks (dot product) dari kedua matriks)\n")

# membuat dua matriks 3x3 dengan angka acak anata 1 dan 10
matriks1 = np.random.randint(1, 11, size=(3, 3))
matriks2 = np.random.randint(1, 11, size=(3, 3))

print(f"Matriks 1: \n {matriks1}")
print(f"Matriks 1: \n {matriks2}")

print("\n=========================================\n")

# Menjumlahkan matriks 1 dan matriks 2
penjumlahan = matriks1 + matriks2
print(f"\nMatriks yang sudah dijumlahkan: \n {penjumlahan}")

# Mengkalikan matriks element-wise
perkalian_elemenwise = matriks1 * matriks2
print(f"\nPerkalian elemen-wise: \n {perkalian_elemenwise}")

# Mengalikan matriks (do product)
perkalian_dot = np.dot(matriks1, matriks2)
print(f"\nPerkalian matriks (dot product): \n {perkalian_dot}")

4. Membuat 2 matriks 3x3 dengan angka acak dan lakukan operasi (menambahkan kedua matriks, mengalikan kedua matriks secara element-wise, mengkalikan matriks (dot product) dari kedua matriks)

Matriks 1: 
 [[8 8 2]
 [1 7 3]
 [9 5 3]]
Matriks 1: 
 [[ 1 10  7]
 [ 9  3 10]
 [ 7 10  8]]



Matriks yang sudah dijumlahkan: 
 [[ 9 18  9]
 [10 10 13]
 [16 15 11]]

Perkalian elemen-wise: 
 [[ 8 80 14]
 [ 9 21 30]
 [63 50 24]]

Perkalian matriks (dot product): 
 [[ 94 124 152]
 [ 85  61 101]
 [ 75 135 137]]
